apiVersion: v1
kind: Service
metadata:
  name: island-ui-dev
  namespace: island-system
spec:
  selector:
    app: island
    component: ui
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 3000
      nodePort: 30700
---
