apiVersion: ami.globalsphare.com/v1alpha1
kind: Application
metadata:
  name: sso-echo
  version: 3.0.0
spec:
  workloads:
    - name: ez
      type: globalsphare.com/v1alpha1/webservice
      vendor: globalsphare.com/v1alpha1/webservice
      properties:
        image: harbor1.zlibs.com/island/ez:alpha
        configs:
          - path: /app
            subPath: id.txt
            data:
              - name: id.txt
                value: "ez"
      traits:
        - type: globalsphare.com/v1alpha1/ingress
  dependencies:
    - name: sso-alpha
      version: ">=0.0.1"
      location: user-defined
      items:
        /*:
          - create
          - read
          - update
          - delete
  userconfigs:
    "$schema": http://json-schema.org/draft-07/schema#
    "$id": http://example.com/product.schema.json
    title: Product
    description: A product from Acme's catalog
    type: object
    properties:
      param1:
        type: integer
      param2:
        type: string
      param3:
        type: object
        properties:
          param3_1:
            type: number
          param3_2:
            type: number
        required:
          - param3_1
      param4:
        type: array
        items:
          type: string
        minItems: 1
        uniqueItems: true
    required:
      - param2