apiVersion: ami.globalsphare.com/v1alpha1
kind: Application
metadata:
  name: containous
  version: 3.0.0
spec:
  workloads:
    - name: containous
      type: webservice
      vendor: webservice
      properties:
        image: containous/whoami
        configs:
          - path: /
            subPath: id.txt
            data:
              - name: id.txt
                value: "containous"
      traits:
        - type: ingress