apiVersion: v1
kind: Service
metadata:
  name: island-setup-dev
spec:
  selector:
    app: island
    component: setup
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 3000
      nodePort: 30500
---