apiVersion: v1
kind: Service
metadata:
  name: island-parser-dev
spec:
  selector:
    app: island
    component: parser
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 3000
      nodePort: 30700
---