apiVersion: ami.globalsphare.com/v1alpha1
kind: Application
metadata:
  name: akali
  version: 3.0.0
spec:
  workloads:
    - name: akali
      type: webservice
      vendor: webservice
      properties:
        image: harbor1.zlibs.com/island/akali:alpha
        port: 3000
        configs:
          - path: /app
            subPath: id.txt
            data:
              - name: id.txt
                value: "akali"
      traits:
        - type: ingress