apiVersion: ami.globalsphare.com/v1alpha1
kind: Application
metadata:
  name: sso
  version: 3.0.0
spec:
  workloads:
    - name: nginx
      type: webservice
      vendor: webservice
      properties:
        image: nginx:1.21
        configs:
          - path: /usr/share/nginx/html
            subPath: user.json
            data:
              - name: user.json
                value: |
                  {"users":["zhangsan", "lisi", "wangwu", "naliu"]}
      traits:
        - type: ingress
  exports:
    /user.json:
      - read