apiVersion: ami.globalsphare.com/v1alpha1
kind: Application
metadata:
  name: zen
  version: 3.0.0
spec:
  workloads:
    - name: alfa
      type: worker
      vendor: worker
      properties:
        image: nginx:1.21
        configs:
          - path: /usr/share/nginx/html/
            subPath: user.json
            data:
              - name: user.json
                value: |
                  {"users":"alfa"}
    - name: bravo
      type: worker
      vendor: worker
      properties:
        after: alfa
        image: nginx:1.21
        configs:
          - path: /usr/share/nginx/html/
            subPath: user.json
            data:
              - name: user.json
                value: |
                  {"users":"bravo"}
    - name: charlie
      type: worker
      vendor: worker
      properties:
        after: bravo
        image: nginx:1.21
        configs:
          - path: /usr/share/nginx/html/
            subPath: user.json
            data:
              - name: user.json
                value: |
                  {"users":"charlie"}
    - name: delta
      type: webservice
      vendor: webservice
      properties:
        after: charlie
        image: nginx:1.21
        configs:
          - path: /usr/share/nginx/html/
            subPath: user.json
            data:
              - name: user.json
                value: |
                  {"users":"delta"}
      traits:
        - type: ingress
