apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: island-ui
  namespace: island-system
spec:
  hosts:
    - "*"
  gateways:
    - crab
  http:
    - route:
        - destination:
            host: island-ui
            port:
              number: 80
---

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: crab
  namespace: island-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "crab.%s"