apiVersion: ami.globalsphare.com/v1alpha1
kind: Application
metadata:
  name: github
  version: 1.0.0
spec:
  workloads:
    - name: ha
      type: webservice
      vendor: webservice
      properties:
        image: harbor1.zlibs.com/island/island-nginx:1.21
      traits:
        - type: ingress
  userconfigs:
    "$schema": http://json-schema.org/draft-07/schema#
    "$id": http://example.com/product.schema.json
    title: Product
    description: A product from Acme's catalog
    type: object
    properties:
      param1:
        type: integer
      param2:
        type: string
      param4:
        type: array
        items:
          type: string
        minItems: 1
        uniqueItems: true
    required:
      - param2