apiVersion: ami.globalsphare.com/v1alpha1
kind: Application
metadata:
  name: jenkins
  version: 3.0.0
spec:
  workloads:
    - name: cache
      type: globalsphare.com/v1alpha1/workloadType/redis
      vendor: globalsphare.com/v1alpha1/workloadVendor/redis
    - name: db
      type: globalsphare.com/v1alpha1/workloadType/mysql
      vendor: globalsphare.com/v1alpha1/workloadVendor/mysql
      properties:
        rootpwd: "123456"
        storage:
          capacity: 1Gi
        init: "CREATE DATABASE island;"
        after: cache
    - name: api
      type: globalsphare.com/v1alpha1/workloadType/webservice
      vendor: globalsphare.com/v1alpha1/workloadVendor/webservice
      properties:
        image: harbor1.zlibs.com/island/island-nginx:1.21
        after: db
        configs:
          - path: /tmp
            subPath: 1.txt
            data:
              - name: 1.txt
                value: "111"
      traits:
        - type: globalsphare.com/v1alpha1/trait/ingress


  dependencies:
    - name: github
      version: ">=0.5.1"
      location: user-defined
      uses:
        /*:
          - create
          - read
          - update
          - delete
    - name: harbor
      version: ">=2.0.0"
      location: user-defined(https://www.github.com)
      uses:
        /*:
          - create
          - read
          - update
          - delete
  userconfigs:
    type: object
    properties:
      param:
        type: string
    required:
      - param