apiVersion: ami.globalsphare.com/v1alpha1
kind: Application
metadata:
  name: ez
  version: 3.0.0
spec:
  workloads:
    - name: ez
      type: globalsphare.com/v1alpha1/webservice
      vendor: globalsphare.com/v1alpha1/webservice
      properties:
        image: harbor1.zlibs.com/island/ez:alpha
        configs:
          - path: /app
            subPath: id.txt
            data:
              - name: id.txt
                value: "ez"
      traits:
        - type: globalsphare.com/v1alpha1/ingress
  dependencies:
    - name: sso
      version: ">=0.0.1"
      location: user-defined
      items:
        /*:
          - create
          - read
          - update
          - delete