
apiVersion: apps/v1
kind: Deployment
metadata:
  name: island-ui
  namespace: island-system
  labels:
    app: island
    component: ui
spec:
  replicas: 1
  template:
    metadata:
      name: island-ui
      labels:
        app: island
        component: ui
    spec:
      containers:
        - name: island-ui
          image: harbor1.zlibs.com/island/island-ui:alpha
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /appManager/config/
              name: conf
      restartPolicy: Always
  selector:
    matchLabels:
      app: island
      component: ui
---
apiVersion: v1
kind: Service
metadata:
  name: island-ui
spec:
  selector:
    app: island
    component: ui
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: island-console-ui
  namespace: island-system
data:
  config.json: |
    {
        "webConfig": {
            "port": 80,
            "requestDomain": "http://island-web"
        }
    }