
apiVersion: v1
kind: ServiceAccount
metadata:
  name: island-db-user
  namespace: island-system
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: island-db-user-building
  namespace: island-system
subjects:
  - kind: ServiceAccount
    name: island-db-user
    apiGroup: ""
    namespace: island-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---

apiVersion: v1
kind: Service
metadata:
  name: island-db
  namespace: island-system
  labels:
    app: island
    component: db
spec:
  type: ClusterIP
  ports:
    - name: port
      port: 3306
      targetPort: 3306
  selector:
    app: island
    component: db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: island-db
  namespace: island-system
  labels:
    app: island
    component: db
spec:
  replicas: 1
  template:
    metadata:
      name: island-db
      labels:
        app: island
        component: db
    spec:
      containers:
        - name: island-db
          image: harbor1.zlibs.com/dockerhub/mysql:5.7
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d/
              name: conf
      volumes:
        - name: conf
          configMap:
            name: island-db
      restartPolicy: Always
      serviceAccountName: island-db-user
  selector:
    matchLabels:
      app: island
      component: db
---
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: island-db
  namespace: island-system
data:
  init.sql: |
    CREATE DATABASE crab;
    USE crab;

    CREATE TABLE `t_app` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT,
    `uuid` varchar(128) COLLATE utf8mb4_bin DEFAULT NULL,
    `status` int(12) DEFAULT NULL,
    `name` varchar(128) COLLATE utf8mb4_bin DEFAULT NULL,
    `version` varchar(128) COLLATE utf8mb4_bin DEFAULT NULL,
    `manifest` longtext COLLATE utf8mb4_bin,
    `deployment` longtext CHARACTER SET utf8mb4,
    `created_at` datetime(3) DEFAULT NULL,
    `updated_at` datetime(3) DEFAULT NULL,
    PRIMARY KEY (`id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
    CREATE TABLE `t_status` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `name` longtext COLLATE utf8mb4_bin,
    `component` longtext COLLATE utf8mb4_bin,
    `status` bigint(20) DEFAULT NULL,
    PRIMARY KEY (`id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;