
apiVersion: v1
kind: Service
metadata:
  name: island-cache
  namespace: island-system
  labels:
    app: island
    component: cache
spec:
  type: ClusterIP
  ports:
    - name: port
      port: 6379
      targetPort: 6379
  selector:
    app: island
    component: cache
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: island-cache
  namespace: island-system
  labels:
    app: island
    component: cache
spec:
  replicas: 1
  template:
    metadata:
      name: island-cache
      labels:
        app: island
        component: cache
    spec:
      containers:
        - name: island-cache
          image: harbor1.zlibs.com/dockerhub/redis:6.2.4
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      serviceAccountName: crab
  selector:
    matchLabels:
      app: island
      component: cache