
apiVersion: v1
kind: Service
metadata:
  name: island-db
  namespace: island-system
  labels:
    app: island
    component: db
spec:
  type: ClusterIP
  ports:
    - name: port
      port: 3306
      targetPort: 3306
  selector:
    app: island
    component: db
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: island-db
  namespace: island-system
data:
  init.sql: |
    CREATE DATABASE crab;
    USE crab;


    DROP TABLE IF EXISTS `t_app`;
    CREATE TABLE `t_app` (
    `pk` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    `id` varchar(128) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '唯一名称',
    `status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '实例状态',
    `name` varchar(128) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '应用名称',
    `version` varchar(128) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '应用版本',
    `configurations` longtext COLLATE utf8mb4_bin NOT NULL COMMENT '应用配置',
    `dependencies` longtext COLLATE utf8mb4_bin NOT NULL COMMENT '应用依赖',
    `manifest` longtext COLLATE utf8mb4_bin NOT NULL COMMENT '应用描述',
    `entry` varchar(128) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '域名',
    `parameters` longtext CHARACTER SET utf8mb4 NOT NULL COMMENT '配置参数',
    `additional` longtext CHARACTER SET utf8mb4 NOT NULL COMMENT '依赖配置',
    `deployment` longtext CHARACTER SET utf8mb4 NOT NULL COMMENT '应用部署',
    `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
    `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '更新时间',
    PRIMARY KEY (`pk`) USING BTREE
    ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

    DROP TABLE IF EXISTS `t_trait`;
    CREATE TABLE `t_trait` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    `name` varchar(128) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '名称',
    `ver` varchar(128) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '版本',
    `value` longtext CHARACTER SET utf8mb4 NOT NULL COMMENT '值',
    `type` tinyint(4) NOT NULL DEFAULT '0' COMMENT '类型0内置不可删除1新增',
    `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
    `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '更新时间',
    PRIMARY KEY (`id`) USING BTREE
    ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

    DROP TABLE IF EXISTS `t_type`;
    CREATE TABLE `t_type` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    `name` varchar(128) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '名称',
    `ver` varchar(128) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '版本',
    `value` longtext CHARACTER SET utf8mb4 NOT NULL COMMENT '值',
    `type` tinyint(4) NOT NULL DEFAULT '0' COMMENT '类型0内置不可删除1新增',
    `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
    `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '更新时间',
    PRIMARY KEY (`id`) USING BTREE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

    DROP TABLE IF EXISTS `t_vendor`;
    CREATE TABLE `t_vendor` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    `name` varchar(128) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '名称',
    `ver` varchar(128) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '版本',
    `value` longtext CHARACTER SET utf8mb4 NOT NULL COMMENT '值',
    `type` tinyint(4) NOT NULL DEFAULT '0' COMMENT '类型0内置不可删除1新增',
    `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
    `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '更新时间',
    PRIMARY KEY (`id`) USING BTREE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: island-db
  namespace: island-system
  labels:
    app: island
    component: db
spec:
  replicas: 1
  template:
    metadata:
      name: island-db
      labels:
        app: island
        component: db
    spec:
      containers:
        - name: island-db
          image: harbor1.zlibs.com/dockerhub/mysql:5.7
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d/
              name: conf
      volumes:
        - name: conf
          configMap:
            name: island-db
      restartPolicy: Always
      serviceAccountName: crab
  selector:
    matchLabels:
      app: island
      component: db

