apiVersion: v1
kind: Service
metadata:
  name: island-api
  namespace: island-system
spec:
  selector:
    app: island
    component: api
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: island-api
  namespace: island-system
  labels:
    app: island
    component: api
spec:
  replicas: 1
  template:
    metadata:
      name: island-api
      labels:
        app: island
        component: api
    spec:
      containers:
        - name: island-api
          image: harbor1.zlibs.com/island/island-api:0.1.0
          imagePullPolicy: Always
      restartPolicy: Always
      serviceAccountName: crab
  selector:
    matchLabels:
      app: island
      component: api



