apiVersion: ami.globalsphare.com/v1alpha1
kind: Application
metadata:
  name: zed
  version: 3.0.0
spec:
  workloads:
    - name: main
      type: webservice
      vendor: webservice
      properties:
        image: harbor1.zlibs.com/tars/orders
        port: 3000
      traits:
        - type: ingress
    - name: db
      type: mysql-bare
      vendor: mysql-bare
      properties:
        init: |
          CREATE DATABASE orders;
          USE orders;
          CREATE TABLE `orders` (
          `pk` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
          `id` varchar(128) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '订单',
          `status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '状态',
          `create_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
          `update_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '更新时间',
          PRIMARY KEY (`pk`) USING BTREE
          ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
          INSERT INTO `orders`.`orders`(`id`, `status`) VALUES ('Order_736-3563777-5518068', 2);
  exports:
    /:
      - read