apiVersion: ami.globalsphare.com/v1alpha1
kind: Application
metadata:
  name: tcp-test
  version: 0.0.1+dev
spec:
  workloads:
    - name: redis-test
      type: webservice
      vendor: webservice
      properties:
        image: harbor1.zlibs.com/crab-demo/hezhongjiang/redis-test
        port: 3000
        configs:
          - path: /app
            subPath: config.yaml
            data:
              - name: config.yaml
                value: |
                  mysql:
                    host: 192.168.0.2
                    port: 3306
                    username: root
                    password: 123456
                    database: orders

                  redis:
                    host: 192.168.0.2
                    port: 6379
                    password:
      traits:
        - type: ingress
  dependencies:
    - name: redis
      version: 0.0.1
      location: tcp://192.168.0.2:6379
    - name: mysql
      version: 0.0.1
      location: tcp://192.168.0.2:3306
    - name: db
      version: 0.0.1
      location: user-defined(tcp://db)