apiVersion: ami.globalsphare.com/v1alpha1
kind: Application
metadata:
  name: harbor
  version: 2.0.0
spec:
  workloads:
    - name: cache
      type: redis
      vendor: redis
    - name: db
      type: redis
      vendor: redis
      properties:
        after: cache
    - name: api
      type: webservice
      vendor: webservice
      properties:
        image: harbor1.zlibs.com/island/island-nginx:1.21
        after: db
        configs:
          - path: /tmp
            subPath: 1.txt
            data:
              - name: 1.txt
                value: "111"
      traits:
        - type: ingress


  dependencies:
    - name: github
      version: ">=0.0.1"
      location: https://www.github.com
      uses:
        /*:
          - create
          - read
          - update
          - delete
    - name: gitlab
      version: ">=0.0.1"
      location: https://www.github.com
      uses:
        /*:
          - create
          - read
          - update
          - delete

  userconfigs:
    "$schema": http://json-schema.org/draft-07/schema#
    "$id": http://example.com/product.schema.json
    title: Product
    description: A product from Acme's catalog
    type: object
    properties:
      param1:
        type: integer
      param2:
        type: string
      param4:
        type: array
        items:
          type: string
        minItems: 1
        uniqueItems: true
    required:
      - param2